### ISSUE TITLE
Allow to specify experiments using regexes

### ISSUE THREAD

**Issue by arielrossanigo** [arielrossanigo/yaer#1]
The idea is to be able to specify what experiments to run using regexes. 
The use will be the same, with -e <name> the experiments are specified, if <name> is a regex, then, all experiments matching that regex will be runned.

**Comment by ifranco14** [comment]
Hi Ariel, 

I've made this change [here](https://github.com/arielrossanigo/yaer/pull/2).  Now the `yaer run` option to match experiments using a regular expression is `-re` (e.g. `yaer run -re '^knn'`) and the -e option is no longer marked as required.

Please let me know if there's something you prefer to be made in a different way,
Nacho.
